version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-secret-password
    volumes:
      - dbdata6:/data/db
  posts:
    image: bharamicrosystems/posts
    build: ./posts
    ports:
      - '5000:5000'
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=super-secret-password
  reviews:
    image: bharamicrosystems/reviews
    build: ./reviews
    ports:
      - '5001:5000'
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=super-secret-password
  ratings:
    image: bharamicrosystems/ratings
    build: ./ratings
    ports:
      - '5002:5000'
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=super-secret-password
  users:
    image: bharamicrosystems/users
    build: ./users
    ports:
      - '5003:5000'
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=super-secret-password
  frontend:
    image: bharamicrosystems/frontend
    build: ./frontend
    ports:
      - '8080:5000'
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=super-secret-password
volumes:
  dbdata6:
